### ISSUE TITLE
CDN not accessible with https connection

### ISSUE THREAD

**Issue by MS-elug** [ariatemplates/cdn.ariatemplates.com#3]
Hello Aria team,

I'm using your cdn for an https website, but the content get blocked by Chrome because only https script can be included in a https website. I tried the protocol https with your CDN but it doesn't work.

Did you plan to activate https for you CDN?
Best regards,
Mathieu

**Comment by benouat** [comment]
Hello Mathieu,

Unfortunately we do not plan to activate `https://` for the cdn.

This cdn has just been setup for development purpose, and __only__ for development purpose where having `https://` activated in usually not that mandatory.

Sorry, you'll have to do it differently if `https://`is absolutely needed during your dev.

**Comment by jakub-g** [comment]
As a workaround, if you use [Fiddler](https://github.com/ariatemplates/fiddler-rules/) to redirect your deployed resources to the CDN (instead of directly targeting the CDN), that should work. You'll need to

- enable HTTPS decryption in Fiddler,
- export Fiddler root cert to desktop
- import Fiddler root cert to any browser you want to use
